Repository Sylius/AdyenPlugin, pull requests merged in 2025-09, with the labels that each got.

#56 Use different anylytics and risk detection script according to the environment
  templates/Shop/_analytics.html.twig
Labels: Maintenance

#57 [ExpressCheckout] Use correct payment method code and make repository methods more specific
  config/services/controller.xml
  src/Controller/Shop/ExpressCheckout/AbstractConfigurationAction.php
  src/Controller/Shop/ExpressCheckout/PayPal/InitializeAction.php
  src/Controller/Shop/ExpressCheckout/ProductConfigurationAction.php
  src/Form/Extension/PaymentTypeExtension.php
  src/Provider/AdyenClientProvider.php
  src/Repository/PaymentMethodRepositoryInterface.php
  src/Repository/PaymentMethodRepositoryTrait.php
  src/Resolver/ExpressCheckout/CheckoutResolver.php
Labels: Bug

#60 [Refactor] Rename `AdyenToken` resource to `ShopperReference`
  assets/shop/js/dropin.js
  config/api_resources/Adyen.xml
  config/doctrine/ShopperReference.orm.xml
  config/services.xml
  config/services/bus.xml
  config/services/factories.xml
  config/services/providers.xml
  config/services/resolvers.xml
  config/services/responders.xml
  config/sylius/resources.yml
  src/Bus/Command/CreateToken.php
  src/Bus/Handler/CreateTokenHandler.php
  src/Bus/Handler/GetTokenHandler.php
  src/Bus/Query/GetToken.php
  src/Client/AdyenClient.php
  src/Client/AdyenClientInterface.php
  src/Client/ClientPayloadFactory.php
  src/Client/ClientPayloadFactoryInterface.php
  src/Controller/Shop/DropinConfigurationAction.php
  src/Controller/Shop/PaymentsAction.php
  src/Controller/Shop/RemoveStoredTokenAction.php
  src/Entity/ShopperReference.php
  src/Entity/ShopperReferenceInterface.php
  src/Factory/ShopperReferenceFactory.php
  src/Factory/ShopperReferenceFactoryInterface.php
  src/Migrations/Version20250903190544.php
  src/Provider/CurrentShopUserProvider.php
  src/Provider/CurrentShopUserProviderInterface.php
  src/Provider/PaymentMethodsForOrderProvider.php
  src/Repository/ShopperReferenceRepository.php
  src/Repository/ShopperReferenceRepositoryInterface.php
  src/Resolver/ShopperReferenceResolver.php
  src/Resolver/ShopperReferenceResolverInterface.php
  tests/Functional/Stub/AdyenClientStub.php
  tests/Unit/Bus/Handler/CreateTokenHandlerTest.php
  tests/Unit/Bus/Handler/GetTokenHandlerTest.php
  tests/Unit/Provider/CurrentShopUserProviderTest.php
  tests/Unit/Resolver/ShopperReferenceResolverTest.php
Labels: DX

#61 [Manual][Refund] After QA Fixes
  src/Menu/AdminOrderShowMenuListener.php
  src/Twig/Extension/AdyenPaymentCheckerExtension.php
  templates/bundles/SyliusRefundPlugin/Order/Admin/_refundPayments.html.twig
  tests/Unit/Menu/AdminOrderShowMenuListenerTest.php
Labels: Bug

#62 Fix changing payment method after placing an order with offline one
  templates/Shop/_dropin.html.twig
  templates/Shop/_payment_choose.html.twig
  templates/bundles/SyliusShopBundle/Checkout/Complete/_navigation.html.twig
Labels: Bug

#65 Add parameters for scalaPay
  src/Client/ClientPayloadFactory.php
  src/Provider/ExpressCheckout/Cart/GooglePayConfigurationProvider.php
  src/Provider/ExpressCheckout/Cart/PaypalConfigurationProvider.php
Labels: Bug

#64 [Manual] Fix reapplied authorization on currently processing payment
  config/services/checkers.xml
  config/winzou_state_machine/sylius_payment.yaml
  src/Checker/AdyenPaymentMethodChecker.php
  src/Checker/AdyenPaymentMethodCheckerInterface.php
  src/StateMachine/Guard/AdyenPaymentGuard.php
  src/StateMachine/Guard/OrderPaymentGuard.php
  tests/Unit/Checker/AdyenPaymentMethodCheckerTest.php
Labels: Bug

#55 Limit available payment methods by configuration
  config/config.yaml
  config/services.xml
  config/services/adyen.xml
  config/services/controller.xml
  config/services/filters.xml
  config/services/forms.xml
  config/services/mappers.xml
  config/sylius_adyen.yaml
  src/Bus/Handler/TakeOverPaymentHandler.php
  src/Client/AdyenClient.php
  src/Client/AdyenClientInterface.php
  src/Client/ClientPayloadFactory.php
  src/Client/PaymentMethodsFilter.php
  src/Controller/Shop/DropinConfigurationAction.php
  src/Controller/Shop/ExpressCheckout/AbstractConfigurationAction.php
  src/Controller/Shop/ExpressCheckout/ProductConfigurationAction.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SyliusAdyenExtension.php
  src/Exception/AdyenPaymentMethodNotFoundException.php
  src/Exception/OrderWithoutCustomerException.php
  src/Filter/ConfiguredPaymentMethodsFilter.php
  src/Filter/PaymentMethodsFilterInterface.php
  src/Filter/StoredPaymentMethodsFilter.php
  src/Filter/StoredPaymentMethodsFilterInterface.php
  src/Form/Extension/PaymentTypeExtension.php
  src/Mapper/AdyenPaymentMethodsMapper.php
  src/Mapper/PaymentMethodsMapperInterface.php
  src/Model/PaymentMethod.php
  src/Model/PaymentMethodData.php
  src/Model/StoredPaymentMethod.php
  src/Provider/AdyenClientProvider.php
  src/Provider/PaymentMethodsForOrderProvider.php
  src/Provider/PaymentMethodsProvider.php
  src/Provider/PaymentMethodsProviderInterface.php
  tests/Functional/AdyenTestCase.php
  tests/Functional/Stub/AdyenClientStub.php
  tests/TestApplication/config/config.yaml
  tests/Unit/Bus/Handler/TakeOverPaymentHandlerTest.php
  tests/Unit/Client/ClientPayloadFactoryTest.php
  tests/Unit/Client/PaymentMethodsFilterTest.php
  tests/Unit/Filter/ConfiguredPaymentMethodsFilterTest.php
  tests/Unit/Filter/StoredPaymentMethodsFilterTest.php
  tests/Unit/Mapper/AdyenPaymentMethodsMapperTest.php
  tests/Unit/Provider/PaymentMethodsProviderTest.php
Labels: Feature

#68 Add configuration for Oney payment method
  assets/shop/js/dropin.js
  config/sylius_adyen.yaml
  src/Provider/PaymentMethodsProvider.php
Labels: Bug

#70 [Maintenance] Remove Adyen SDK deprecations
  src/Client/AdyenClient.php
  src/Client/AdyenClientInterface.php
  src/Client/ClientPayloadFactory.php
  src/Client/ClientPayloadFactoryInterface.php
  src/Controller/Shop/ExpressCheckout/PayPal/ShippingAddressChangeAction.php
  src/Controller/Shop/ExpressCheckout/PayPal/ShippingOptionsChangeAction.php
  tests/Functional/Stub/AdyenClientStub.php
  tests/Unit/Client/ClientPayloadFactoryTest.php
Labels: Enhancement, Maintenance

#72 Add validation for checkout completion
  config/services/checkers.xml
  config/services/controller.xml
  config/services/resolvers.xml
  config/services/responders.xml
  src/Checker/Eligibility/ZoneShippingMethodEligibilityChecker.php
  src/Checker/OrderCheckoutCompleteIntegrityChecker.php
  src/Checker/OrderCheckoutCompleteIntegrityCheckerInterface.php
  src/Controller/Shop/ExpressCheckout/GooglePay/CheckoutAction.php
  src/Controller/Shop/ExpressCheckout/PayPal/CheckoutAction.php
  src/Controller/Shop/PaymentDetailsAction.php
  src/Controller/Shop/PaymentsAction.php
  src/Exception/CheckoutValidationException.php
  src/Resolver/ExpressCheckout/CheckoutResolver.php
  src/Traits/PayableOrderPaymentTrait.php
  tests/Functional/AdyenTestCase.php
  tests/Unit/Checker/Eligibility/ZoneShippingMethodEligibilityCheckerTest.php
  tests/Unit/Checker/OrderCheckoutCompleteIntegrityCheckerTest.php
  translations/messages.en.yaml
Labels: Bug

#80 [Checkout] Fix saved methods accessing
  config/services.xml
  src/Provider/PaymentMethodsProvider.php
  tests/Unit/Provider/PaymentMethodsProviderTest.php
Labels: Bug, Shop

#91 Support Symfony Workflow
  .github/workflows/build.yaml
  config/config.yaml
  config/services.xml
  config/services/workflow/order.xml
  config/services/workflow/order_payment.xml
  config/services/workflow/payment.xml
  config/services/workflow/refund_refund_payment.xml
  config/winzou_state_machine/sylius_order_payment.yaml
  config/workflow/sylius_payment.yaml
  config/workflow/sylius_refund_refund_payment.yaml
  src/DependencyInjection/Compiler/AbstractWorkflowTransitionPass.php
  src/DependencyInjection/Compiler/AddOrderPaymentWorkflowTransitionPass.php
  src/DependencyInjection/Compiler/AddPaymentWorkflowTransitionPass.php
  src/DependencyInjection/Compiler/RemoveCancelPaymentListenerPass.php
  src/EventListener/Workflow/Order/GuardCancelOrderListener.php
  src/EventListener/Workflow/Order/RequestCancelOnCancelListener.php
  src/EventListener/Workflow/Order/ReversePaymentOnCancelListener.php
  src/EventListener/Workflow/OrderPayment/GuardCancelListener.php
  src/EventListener/Workflow/OrderPayment/GuardRequestPaymentListener.php
  src/EventListener/Workflow/Payment/AutoCaptureOnAuthorizeListener.php
  src/EventListener/Workflow/Payment/FlushOnFailListener.php
  src/EventListener/Workflow/Payment/GuardAuthorizeListener.php
  src/EventListener/Workflow/Payment/GuardCancelListener.php
  src/EventListener/Workflow/Payment/GuardCompleteListener.php
  src/EventListener/Workflow/Payment/ProcessFailedPaymentOrderListener.php
  src/EventListener/Workflow/Payment/ProcessOrderPaymentAfterReversalListener.php
  src/EventListener/Workflow/Payment/ResolveFailedPaymentStateListener.php
  src/EventListener/Workflow/Payment/ResolveStateListener.php
  src/EventListener/Workflow/Refund/ProcessRefundPaymentOnConfirmListener.php
  src/EventListener/Workflow/Refund/ResolveOrderFullyRefundedListener.php
  src/SyliusAdyenPlugin.php
  tests/TestApplication/config/config.yaml
  tests/TestApplication/config/sylius_state_machine_abstraction.yaml
  tests/Unit/DependencyInjection/Compiler/AddOrderPaymentWorkflowTransitionPassTest.php
  tests/Unit/DependencyInjection/Compiler/AddPaymentWorkflowTransitionPassTest.php
  tests/Unit/DependencyInjection/Compiler/RemoveCancelPaymentListenerPassTest.php
  tests/Unit/EventListener/Workflow/Order/GuardCancelOrderListenerTest.php
  tests/Unit/EventListener/Workflow/Order/RequestCancelOnCancelListenerTest.php
  tests/Unit/EventListener/Workflow/Order/ReversePaymentOnCancelListenerTest.php
  tests/Unit/EventListener/Workflow/OrderPayment/GuardCancelListenerTest.php
  tests/Unit/EventListener/Workflow/OrderPayment/GuardRequestPaymentListenerTest.php
  tests/Unit/EventListener/Workflow/Payment/AutoCaptureOnAuthorizeListenerTest.php
  tests/Unit/EventListener/Workflow/Payment/FlushOnFailListenerTest.php
  tests/Unit/EventListener/Workflow/Payment/GuardAuthorizeListenerTest.php
  tests/Unit/EventListener/Workflow/Payment/GuardCancelListenerTest.php
  tests/Unit/EventListener/Workflow/Payment/GuardCompleteListenerTest.php
  tests/Unit/EventListener/Workflow/Payment/ProcessFailedPaymentOrderListenerTest.php
  tests/Unit/EventListener/Workflow/Payment/ProcessOrderPaymentAfterReversalListenerTest.php
  tests/Unit/EventListener/Workflow/Payment/ResolveFailedPaymentStateListenerTest.php
  tests/Unit/EventListener/Workflow/Payment/ResolveStateListenerTest.php
  tests/Unit/EventListener/Workflow/Refund/ProcessRefundPaymentOnConfirmListenerTest.php
  tests/Unit/EventListener/Workflow/Refund/ResolveOrderFullyRefundedListenerTest.php
  tests/Unit/Processor/Order/UpdateOrderPaymentProcessorTest.php
Labels: Feature

#93 [PaymentMethods] Allow configuring methods not available for guests and forcing manual mode
  composer.json
  config/services/checkers.xml
  config/services/factories.xml
  config/services/filters.xml
  src/Checker/AdyenPaymentMethodChecker.php
  src/Controller/Shop/PaymentsAction.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SyliusAdyenExtension.php
  src/Factory/AdyenPaymentDetailFactory.php
  src/Filter/GuestPaymentMethodsFilter.php
  src/Provider/PaymentMethodsProvider.php
  tests/Functional/AdyenTestCase.php
  tests/Functional/OrderProcessing/CheckoutTest.php
  tests/Unit/Checker/AdyenPaymentMethodCheckerTest.php
  tests/Unit/Factory/AdyenPaymentDetailFactoryTest.php
  tests/Unit/Filter/GuestPaymentMethodsFilterTest.php
Labels: Feature

#95 [Admin] Fix payment link button on order show
  templates/admin/order/content/sections/payments/item/actions/send_payment_link.html.twig
Labels: Admin, Bug

#98 Enable Apple Pay payment method
  config/sylius_adyen.yaml
Labels: Feature

#90 [ExpressCheckout][Cart] Add ApplePay
  assets/shop/js/express-checkout/cart/applepay.js
  assets/shop/js/express-checkout/cart/googlepay.js
  assets/shop/js/express-checkout/cart/main.js
  assets/shop/js/express-checkout/product/applepay.js
  assets/shop/js/express-checkout/product/main.js
  config/routes/shop/express_checkout.yaml
  config/services/controller.xml
  config/services/modifier.xml
  config/services/provider.xml
  src/Controller/Shop/ExpressCheckout/ApplePay/CheckoutAction.php
  src/Controller/Shop/ExpressCheckout/ApplePay/ShippingAddressChangeAction.php
  src/Controller/Shop/ExpressCheckout/ApplePay/ShippingOptionsChangeAction.php
  src/Controller/Shop/ExpressCheckout/PayPal/ShippingOptionsChangeAction.php
  src/Modifier/ExpressCheckout/ApplePay/OrderAddressModifier.php
  src/Modifier/ExpressCheckout/ApplePay/OrderAddressModifierInterface.php
  src/Provider/ExpressCheckout/ApplePay/ShippingMethodsProvider.php
  src/Provider/ExpressCheckout/ApplePay/ShippingMethodsProviderInterface.php
  src/Provider/ExpressCheckout/ApplePay/TransactionInfoProvider.php
  src/Provider/ExpressCheckout/ApplePay/TransactionInfoProviderInterface.php
  src/Provider/ExpressCheckout/Cart/ApplePayConfigurationProvider.php
  tests/Unit/Modifier/ExpressCheckout/ApplePay/OrderAddressModifierTest.php
  tests/Unit/Provider/ExpressCheckout/ApplePay/ShippingMethodsProviderTest.php
  tests/Unit/Provider/ExpressCheckout/ApplePay/TransactionInfoProviderTest.php
  tests/Unit/Provider/ExpressCheckout/Cart/ApplePayConfigurationProviderTest.php
Labels: Feature, Shop

#119 [ExpressCheckout][Product] Handle the cart changes in parallel with ApplePay initiated on product page
  assets/shop/js/express-checkout/cart/applepay.js
  assets/shop/js/express-checkout/product/applepay.js
Labels: Bug, Shop

#116 [Maintenance] Fix migrations and add initial migration for postgres
  .github/workflows/build.yaml
  src/Migrations/Version20220426141106.php
  src/Migrations/Version20250901091624.php
  src/Migrations/Version20250924125900.php
Labels: Bug, Enhancement

#115 [Maintenance] Enhance configuration and fix refund config loading
  composer.json
  config/config.yaml
  config/sylius/resources.yml
  config/winzou_state_machine/sylius_refund_refund_payment.yaml
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SyliusAdyenExtension.php
  tests/TestApplication/config/config.yaml
Labels: DX, Enhancement, Maintenance

#122 [Maintenance] Add license files
  LICENSE
  LICENSE_OF_TRADEMARK_AND_LOGO
Labels: Maintenance

#132 [Composer] Minor dependency clean up
  composer.json
  config/sylius_adyen.yaml
Labels: Dependencies, Maintenance

#134 [Admin] Move Adyen menu to payment method index page
  config/grids/admin/payment_method.yaml
  config/services.xml
  src/Menu/AdminMainMenuListener.php
Labels: Admin, UX
